name = "timezones"
main = "src/index.ts"
compatibility_date = "2023-05-15"
usage_model = "bundled"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "TimezonesDB"
database_id = "SAME_DB_ID"
preview_database_id = "SAME_DB_ID"

[triggers]
crons = []

[build]
command = "npm run build"

[vars]
api_url = "ApiURLHere"
pages_url = "PagesURLHere"
cookie_secret = "CookieSecretHere"
discord_client_id = "ClientIDHere"

# discord_token, discord_public_key, discord_client_secret
# should be set using:
# echo VALUE | wrangler secret put KEY
